#!/bin/bash

enables_list=(layoutex icuio tools extras tests samples)

# utils are needed to compile the data so we enable it
enables_in=(tools)

options=()

while [ ! -z ${1+x} ]; do
    case $1 in
    -icuio)
        enables_in+=(icuio)
        ;;
    -layoutex)
        enables_in+=(layoutex)
        ;;
    *)
        options+=("$1")
        ;;
    esac
    shift
done

for opt in "${enables_list[@]}"; do
    if [[ " ${enables_in[*]} " == *" $opt "* ]]; then
        options+=(--enable-$opt)
    else
        options+=(--disable-$opt)
    fi
done

# files    raw files (.res, etc)
# archive  build a single icudtXX.dat file
# library  shared library (.dll/.so/etc.)
# static   static library (.a/.lib/etc.)
# auto     build shared if possible (default)
#    See https://unicode-org.github.io/icu/userguide/icu_data for more info.
if [[ "$OSTYPE" == "msys"* || "$OSTYPE" == "mingw"* || $OSTYPE == "cygwin"* ]]; then
    # --disable-rpath is added because it is used by MSYS2 build recipe.
    # MSYS2 in addition use "dll" for packaging so we do the same.
    options+=(--disable-rpath --with-data-packaging=dll)
else
    options+=(--with-data-packaging=archive)
fi

enter_git_repository "https://github.com/lhelper-org/icu" "release-${version}-lhelper"
cd icu4c/source
build_and_install configure "${options[@]}"
